### ISSUE TITLE
Migrate Existing Documentation to GitHub Wiki

### ISSUE THREAD

**Issue by aspickard** [dasher-project/redash#62]

**Comment by sjjhsjjh** [comment]
Hi Adam, What would be the benefit of moving the documentation to the wiki please?

**Comment by willwade** [comment]
Hi Jim. We've been back and forth. I think last plan is not to migrate but we just link to it from wiki / developer onboarding guides eg see doc on https://github.com/dasher-project/dasher-captivewebview/wiki 

So we should be able to close this

**Comment by aspickard** [comment]
Copying what Will said, basically just wanted to make the developer documentation available there
